services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.2-management
    hostname: platforms-rabbit
    volumes:
      - ./conf/definitions.json:/etc/rabbitmq/definitions.json:rw
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:rw
      - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins:rw
      - ./datas:/var/lib/rabbitmq:rw
    environment:
      - RABBITMQ_FEATURE_FLAGS=classic_mirrored_queue_version,classic_queue_type_delivery_support,delete_ra_cluster_mqtt_node,detailed_queues_endpoint,direct_exchange_routing_v2,drop_unroutable_metric,empty_basic_get_metric,feature_flags_v2,implicit_default_bindings,listener_records_in_ets,maintenance_mode_status,message_containers,mqtt_v5,quorum_queue,quorum_queue_non_voters,rabbit_mqtt_qos0_queue,restart_streams,stream_filtering,stream_queue,stream_sac_coordinator_unblock_group,stream_single_active_consumer,stream_update_config_command,tracking_records_in_ets,user_limits,virtual_host_metadata
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883 
      - 5551:5551 
      - 5552:5552 
